<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>TastyAdrenaline</RootNamespace>
        <AssemblyName>TastyAdrenaline</AssemblyName>
        <LangVersion>10</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Deterministic>true</Deterministic>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
        <Optimize>false</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>portable</DebugType>
        <Optimize>true</Optimize>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="JotunnLib" Version="2.26.1" />
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3"
            PrivateAssets="All" />
    </ItemGroup>
    <Target Name="PublishModOnUnix" AfterTargets="Build" Condition="'$(OS)' == 'Unix'">
        <Exec
            Command="sh &quot;$(MSBuildProjectDirectory)/scripts/publish.sh&quot; --target &quot;$(Configuration)&quot; --target-path &quot;$(TargetDir)&quot; --target-assembly &quot;$(TargetFileName)&quot; --project-path &quot;$(MSBuildProjectDirectory)&quot;" />
    </Target>
    <Target Name="PublishModOnWindows" AfterTargets="Build"
        Condition="'$(OS)' == 'Windows_NT' and '$(Configuration)' == 'Release'">
        <MakeDir Directories="$(MSBuildProjectDirectory)\Package\plugins" />
        <Copy SourceFiles="$(TargetPath)"
            DestinationFolder="$(MSBuildProjectDirectory)\Package\plugins" />
    </Target>
</Project>